# Generated by Django 4.2.16 on 2025-07-18 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_itemfavorite_itemview_alter_item_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('electronics', 'Electronics & Appliances'), ('fashion_beauty', 'Fashion & Beauty'), ('home_furniture', 'Home & Furniture'), ('vehicles_auto', 'Vehicles & Auto Parts'), ('property_real_estate', 'Property & Real Estate'), ('jobs_services', 'Jobs & Services'), ('agriculture_food', 'Agriculture & Food'), ('health_wellness', 'Health & Wellness'), ('kids_baby', 'Kids & Baby'), ('education_training', 'Education & Training'), ('events_entertainment', 'Events & Entertainment'), ('others', 'Others')], default='other', max_length=50),
        ),
    ]
